stages:
  - build

before_script:
  - apt-get update 
    && apt-get -y install cmake
    && apt-get -y install python
    && pip install conan

DebugBuild:
  stage: build
  script:
    - scripts/build-x64-debug.sh

ReleaseBuild:
  stage: build
  script:
    - scripts/build-x64-release.sh